services:
  blockchain:
    image: ghcr.io/foundry-rs/foundry:latest
    command: anvil --host 0.0.0.0 --port 8545
    ports:
      - "8545:8545"

  deployer:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - blockchain
    command: sh ./docker/entrypoint.sh
